INSERT INTO artists (artist_name, image_link) VALUES ('A Great Big World and Christina Aguilera', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Auli''i Cravalho', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Fun. ft. Janelle Monáe', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Aladdin', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Idina Menzel', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Backstreet Boys', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Britney Spears', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('吴宗宪 & 温岚', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Spice Girls', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('*NSYNC', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Westlife', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('周杰倫', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Say Something', 1, '-2U0Ivkn2Ds', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('How Far I''ll Go', 2, 'cPAbx5kgCJo', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('We are Young', 3, 'Sv6dMFF_yts','Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('A Whole New World', 4, 'aeDYx7Tkc7I', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Let It Go', 5, 'L0MK7qz13bU', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('I Want It That Way', 6, '4fndeDfaWCg', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Baby One More Time', 7, 'C-u5WLJ9Yk4', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('屋顶', 8, 'hBQ7zeX_GRA', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Wannabe', 9, 'gJLIiF15wjQ', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Bye Bye Bye', 10, 'Eo-KmOd3i7s', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('If I Let You Go', 11, '7NrQei36fJk', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('不愛我就拉倒', 12, 'MAjY8mCTXWk', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO sessions (session_name) VALUES ('emo monday');
INSERT INTO sessions (session_name) VALUES ('retro');
INSERT INTO sessions (session_name) VALUES ('boyband');
INSERT INTO sessions (session_name) VALUES ('chinese hits');
INSERT INTO sessions (session_name) VALUES ('ost');

INSERT INTO sessions_songs (session_id, song_id) VALUES (1,1);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,2);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,3);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,4);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,5);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,6);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,7);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,8);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,9);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,10);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,11);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,12);
INSERT INTO sessions_songs (session_id, song_id) VALUES (2,8);
INSERT INTO sessions_songs (session_id, song_id) VALUES (2,9);
INSERT INTO sessions_songs (session_id, song_id) VALUES (2,7);
INSERT INTO sessions_songs (session_id, song_id) VALUES (3,6);
INSERT INTO sessions_songs (session_id, song_id) VALUES (3,10);
INSERT INTO sessions_songs (session_id, song_id) VALUES (3,11);
INSERT INTO sessions_songs (session_id, song_id) VALUES (3,3);
INSERT INTO sessions_songs (session_id, song_id) VALUES (4,8);
INSERT INTO sessions_songs (session_id, song_id) VALUES (4,12);
INSERT INTO sessions_songs (session_id, song_id) VALUES (5,2);
INSERT INTO sessions_songs (session_id, song_id) VALUES (5,4);
INSERT INTO sessions_songs (session_id, song_id) VALUES (5,5);
