INSERT INTO artists (artist_name, image_link) VALUES ('A Great Big World and Christina Aguilera', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Auli''i Cravalho', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Fun.', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Aladdin', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Idina Menzel', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Backstreet Boys', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Britney Spears', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('吴宗宪 & 温岚', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Spice Girls', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('*NSYNC', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Westlife', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('周杰倫', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Bruno Mars', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Taylor Swift', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Ed Sheeran', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Katy Perry', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('James Arthur', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');


INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Say Something', 1, '-2U0Ivkn2Ds', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('How Far I''ll Go', 2, 'cPAbx5kgCJo', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('We are Young', 3, 'Sv6dMFF_yts','Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('A Whole New World', 4, 'aeDYx7Tkc7I', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Let It Go', 5, 'L0MK7qz13bU', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('I Want It That Way', 6, '4fndeDfaWCg', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Baby One More Time', 7, 'C-u5WLJ9Yk4', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('屋顶', 8, 'hBQ7zeX_GRA', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Wannabe', 9, 'gJLIiF15wjQ', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Bye Bye Bye', 10, 'Eo-KmOd3i7s', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('If I Let You Go', 11, '7NrQei36fJk', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('不愛我就拉倒', 12, 'MAjY8mCTXWk', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint. Beef ribs tenderloin esse alcatra. Leberkas nisi ball tip chicken rump, brisket drumstick tail. Porchetta id duis ham tail, pork venison. Cow adipisicing shank, pork nulla flank pastrami. Ullamco sed jerky sausage in, minim strip steak cupidatat beef ribs. Burgdoggen sirloin in shoulder beef ribs aute proident cow landjaeger kielbasa tri-tip doner tempor. Doner labore excepteur corned beef, dolor esse beef ribs drumstick id short loin turducken sausage. Biltong rump chicken burgdoggen, pig tail elit pancetta qui id eu sint frankfurter capicola. Strip steak ham eu, excepteur dolor cillum est leberkas salami veniam nulla pork chop. Tempor velit ground round nulla.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('24K Magic', 13, 'UqyT8IEBkvY', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Treasure', 13, 'nPvuNsRccVw', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Cruel Summer', 14, 'GrKQvyXpNgc', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('We Are Never Ever Getting Back Together', 14, 'WA4iX5D9Z64', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Love Story', 14, '8xg3vE8Ie_E', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Shake It Off', 14, 'nfWlot6h_JM', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Look What You Made Me Do', 14, '3tmd-ClpJxA', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('The Lazy Song', 13, 'fLexgOxsZu0', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Versace on the Floor', 13, '-FyjEnoIgTM', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('That''s What I Like', 13, 'PMivT7MJ41M', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Grenade', 13, 'SR6iYWJxHqs', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('聽見下雨的聲音', 12, 'zqKoXPHhmsM', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('給我一首歌的時間', 12, 'wt0RKW3aC84', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('算什麼男人', 12, 'HBqyVv13uL0', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('告白氣球', 12, 'cGUx6verzZM', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Thinking Out Loud', 15, 'lp-EO5I60KA', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Photograph', 15, 'nSDgHBxUbVQ', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Shape of You', 15, 'JGwWNGJdvx8', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Castle on the Hill', 15, 'K0ibBPhiaG0', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Happier', 15, 'iWZmdoY1aTE', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Some Nights', 3, 'qQkBeOisNM0', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Small Talk', 16, 'YqunQaPQumk', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Never Really Over', 16, 'aEb5gNsmGJ8', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Roar', 16, 'CevxZvSJLk8', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Say You Won''t Let Go', 17, '0yW7w8F2TVA', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Falling Like The Stars', 17, 'PMGY8fLwess', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO songs (song_name, artist_id, video_link, lyrics) VALUES ('Can I Be Him', 17, 'L3dPK8tDn6g', 'Bacon ipsum dolor amet prosciutto veniam strip steak burgdoggen tenderloin. Sausage aliquip drumstick shankle ball tip prosciutto anim beef cillum sunt meatloaf id meatball officia incididunt. Fatback nostrud exercitation occaecat, nulla magna est filet mignon laboris boudin pork loin short ribs. Porchetta mollit ham jowl. Ex consequat reprehenderit dolore eiusmod, pancetta laboris jerky sed pastrami sint.');

INSERT INTO sessions (session_name) VALUES ('emo monday');
INSERT INTO sessions (session_name) VALUES ('retro');
INSERT INTO sessions (session_name) VALUES ('boyband');
INSERT INTO sessions (session_name) VALUES ('chinese hits');
INSERT INTO sessions (session_name) VALUES ('ost');

INSERT INTO sessions_songs (session_id, song_id) VALUES (1,1);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,2);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,3);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,4);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,5);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,6);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,7);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,8);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,9);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,10);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,11);
INSERT INTO sessions_songs (session_id, song_id) VALUES (1,12);
INSERT INTO sessions_songs (session_id, song_id) VALUES (2,8);
INSERT INTO sessions_songs (session_id, song_id) VALUES (2,9);
INSERT INTO sessions_songs (session_id, song_id) VALUES (2,7);
INSERT INTO sessions_songs (session_id, song_id) VALUES (3,6);
INSERT INTO sessions_songs (session_id, song_id) VALUES (3,10);
INSERT INTO sessions_songs (session_id, song_id) VALUES (3,11);
INSERT INTO sessions_songs (session_id, song_id) VALUES (3,3);
INSERT INTO sessions_songs (session_id, song_id) VALUES (4,8);
INSERT INTO sessions_songs (session_id, song_id) VALUES (4,12);
INSERT INTO sessions_songs (session_id, song_id) VALUES (5,2);
INSERT INTO sessions_songs (session_id, song_id) VALUES (5,4);
INSERT INTO sessions_songs (session_id, song_id) VALUES (5,5);