INSERT INTO artists (artist_name, image_link) VALUES ('A Great Big World', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Auli''i Cravalho', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Fun.', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Aladdin', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Idina Menzel', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Backstreet Boys', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Britney Spears', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('吴宗宪 & 温岚', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Spice Girls', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('*NSYNC', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Westlife', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Jay Chou', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Bruno Mars', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Taylor Swift', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Ed Sheeran', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Katy Perry', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('James Arthur', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Maroon 5', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Chris Brown', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Brian McKnight', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Sixpence None The Richer', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Shawn Mendes', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Adele', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('John Legend', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Christina Perri', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('The Calling', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Gotye', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Vanessa Carlton', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Lewis Capaldi', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('John Mayer', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Sam Smith', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Bigbang', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('2NE1', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Super Junior', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('宇多田ヒカル', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Misia', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('童子-T', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('SHINee', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('OneRepublic', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('The Script', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Daniel Powter', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Ariana Grande', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Jessie J', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Carly Rae Jepsen', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Whitney Houston', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Michael Jackson', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('林俊傑 JJ Lin', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Charlie Puth', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Miley Cyrus', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Sia', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');
INSERT INTO artists (artist_name, image_link) VALUES ('Post Malone', 'https://www.billboard.com/files/styles/article_main_image/public/media/lady-gaga-march-17-2019-u-billboard-1548.jpg');

INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Say Something', 1, '-2U0Ivkn2Ds');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('How Far I''ll Go', 2, 'cPAbx5kgCJo');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('We are Young', 3, 'Sv6dMFF_yts');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('A Whole New World', 4, 'aeDYx7Tkc7I');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Let It Go', 5, 'L0MK7qz13bU');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('I Want It That Way', 6, '4fndeDfaWCg');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Baby One More Time', 7, 'C-u5WLJ9Yk4');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('屋顶', 8, 'hBQ7zeX_GRA');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Wannabe', 9, 'gJLIiF15wjQ');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Bye Bye Bye', 10, 'Eo-KmOd3i7s');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('If I Let You Go', 11, '7NrQei36fJk');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('不愛我就拉倒', 12, 'MAjY8mCTXWk');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('24K Magic', 13, 'UqyT8IEBkvY');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Treasure', 13, 'nPvuNsRccVw');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Cruel Summer', 14, 'GrKQvyXpNgc');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('We Are Never Ever Getting Back Together', 14, 'WA4iX5D9Z64');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Love Story', 14, '8xg3vE8Ie_E');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Shake It Off', 14, 'nfWlot6h_JM');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Look What You Made Me Do', 14, '3tmd-ClpJxA');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('The Lazy Song', 13, 'fLexgOxsZu0');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Versace on the Floor', 13, '-FyjEnoIgTM');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('That''s What I Like', 13, 'PMivT7MJ41M');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Grenade', 13, 'SR6iYWJxHqs');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('聽見下雨的聲音', 12, 'zqKoXPHhmsM');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('給我一首歌的時間', 12, 'wt0RKW3aC84');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('算什麼男人', 12, 'HBqyVv13uL0');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('告白氣球', 12, 'cGUx6verzZM');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Thinking Out Loud', 15, 'lp-EO5I60KA');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Photograph', 15, 'nSDgHBxUbVQ');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Shape of You', 15, 'JGwWNGJdvx8');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Castle on the Hill', 15, 'K0ibBPhiaG0');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Happier', 15, 'iWZmdoY1aTE');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Some Nights', 3, 'qQkBeOisNM0');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Small Talk', 16, 'YqunQaPQumk');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Never Really Over', 16, 'aEb5gNsmGJ8');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Roar', 16, 'CevxZvSJLk8');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Say You Won''t Let Go', 17, '0yW7w8F2TVA');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Falling Like The Stars', 17, 'PMGY8fLwess');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Can I Be Him', 17, 'L3dPK8tDn6g');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Girls Like You ft. Cardi B', 18);
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Galway Girl', 15, '87gWaABqGYs');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Back To Love', 19, 'r7CWEE3ZAWs');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Sugar', 18, '09R8_2nJtjg');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Payphone ft. Wiz Khalifa', 18, 'KRaWnd3LJfs');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Misery', 18, '6g6g2mvItp4');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Shape Of My Heart', 6, 'OT5msu-dap8');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Chances', 6, 'W5kM5wAwRug');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Back At One', 20, 'rXPfovXw2tw');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Somebody That I Used to Know', 27, '8UVNT4wvIGY');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Uptown Girl', 11, '0HTexqxo1og');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Wherever You Will Go', 26, 'iAP9AF6DCu4');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('A Thousand Miles', 28, 'Cwkej79U3ek');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('A Thousand Years', 25, 'rtOvBOTyX00');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('All Of Me', 24, '450p7goxZqg');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Kiss Me', 21, 'v45F0YesdZM');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('There She Goes', 21, '68MKLkNSMN4');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('She Will Be Loved', 18, 'nIjVuRTm-dc');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Mercy', 22, 'KkGVmN68ByU');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Señorita', 22, 'Pkh8UtuejGw');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('If I Can''t Have You', 22, 'oTJ-oqwxdZY');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Someone You Loved', 29, 'zABLecsR5UE');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('South of the Border ft. Cardi B', 15, '_KSKeR2juTI');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Set Fire To The Rain', 23, 'Ri7-vnrJD3k');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Hello', 23, 'YQHsXMglC9A');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Someone Like You', 23, 'hLQl3WQQoQ0');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Waiting On the World to Change', 30, 'oBIxScJ5rlY');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('New Light', 30, 'mQ055hHdxbE');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Carry Me Away', 30, '6YDwBktDthA');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Too Good At Goodbyes', 31, 'J_ub7Etch2U');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Stay With Me', 31, 'pB-5XG-DbAA');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('뱅뱅뱅', 32, '2ips2mM7Zqw');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('내가 제일 잘 나가', 33, 'j7_lSP8Vc3o');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('슈퍼주니어 ''쏘리 쏘리', 34, 'x6QA3m58DQw');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('슈퍼주니어', 34, 'r6TwzSGYycM');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('우리 사랑하지 말아요', 32, '9jTo6hTZmiQ');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('그리워해요', 33, 'AG0jlKdB1s0');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('逢いたくていま', 36, 'MYo5alIaUOk');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('忘れない日々', 36, '7-xChqpitwQ');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('花束を君に', 35, 'yCZFof7Y0tQ');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('光', 35, 'AlMdDpUWFFI');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Lucifer', 38, 'Dww9UjJ4Dt8');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Wanted', 39, 'N_qFfQ3xHCw');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Stop and Stare', 39, 'HtNS1afUOnE');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Counting Stars', 39, 'hT_nvWreIhg');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Start Again ft. Logic', 39, 'y-2VKeDBPkw');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Hall of Fame ft. will.i.am', 40, 'mk48xRzuNvA');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('The Man Who Can''t Be Moved ', 40, 'gS9o1FAszdk');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Superheroes', 40, 'WIm1GgfRz6M');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Bad Day', 41, 'gH476CxJxfg');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('7 rings', 42, 'QYh6mYIJG2Y');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Side To Side ft. Nicki Minaj', 42, 'SXiSVQZLje8');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Problem ft. Iggy Azalea', 42, 'iS1g8G_njx8');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Bang Bang ft. Ariana Grande, Nicki Minaj', 43, '0HDdjwpPM3Y');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Flashlight (from Pitch Perfect 2)', 43, 'DzwkcbTQ7ZE');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Price Tag ft. B.o.B', 43, 'qMxX-QOV9tI');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Domino', 43, 'UJtB55MaoD0');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('I Really Like You', 44, 'qV5lzRHrGeg');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Now That I Found You', 44, 'CnGjfxJqf6I');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Call Me Maybe', 44, 'fWNaR-rxAic');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Too Much', 44, 'rJw32FXV97A');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('I Wanna Dance With Somebody', 45, 'eH3giaIzONA');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Higher Love', 45, 'JR49dyo-y0E');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Saving All My Love For You', 45, 'ewxmv2tyeRs');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('I Will Always Love You', 45, '3JWTaaS7LdU');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('It''s Not Right But It''s Okay', 45, '6J538b-OLRU');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Man In The Mirror', 46, 'PivWY9wn5ps');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('對的時間點', 47, 'gORotxnPczg');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('可惜沒如果', 47, 'vsBf_0gDxSM');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('手心的薔薇 feat. G.E.M. 鄧紫棋', 47, 'onYP5u0b3yw');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('關鍵詞', 47, 'YFr6p7vB9hc');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('黑暗騎士', 47, 'gvce2ywrSsI');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('I Warned Myself', 48, 'wjIes1eGAw4');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Done For Me (feat. Kehlani)', 48, 'TdyllLZeviY');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('We Don''t Talk Anymore (feat. Selena Gomez)', 48, '3AtDnEC4zak');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Marvin Gaye ft. Meghan Trainor', 48, 'igNVdlXhKcI');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('One Call Away', 48, 'BxuY9FET9Y4');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Slide Away', 49, 'rrvFv6j3-sM');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Party In The U.S.A.', 49, 'M11SvDtPBhA');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Malibu', 49, '8j9zMok6two');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Adore You', 49, 'W1tzURKYFNs');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Chandelier', 50, '2vjPBrBU-TM');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Sunflower', 51, 'ApXoWvfEYVU');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Better Now', 51, 'UYwF-jdcVjY');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Circles', 51, 'wXhTHyIgQ_U');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('What Lovers Do ft. SZA', 18, '5Wiio4KoGe8');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Moves Like Jagger ft. Christina Aguilera', 18, 'iEPTlhBmwRg');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Makes Me Wonder', 18, 'sAebYQgy4n4');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Won''t Go Home Without You', 18, 'VlMEGBsw6j8');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Swish Swish ft. Nicki Minaj', 16, 'iGk5fR-t5AU');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('This Is How We Do', 16, '7RMQksXpQSk');
INSERT INTO songs (song_name, artist_id, video_link) VALUES ('Dark Horse ft. Juicy J', 16, '0KSOMA3QBU0');

INSERT INTO sessions (session_name) VALUES ('emo monday');
INSERT INTO sessions (session_name) VALUES ('retro');
INSERT INTO sessions (session_name) VALUES ('boyband');
INSERT INTO sessions (session_name) VALUES ('chinese hits');
INSERT INTO sessions (session_name) VALUES ('ost');

INSERT INTO sessions_songs (session_id, song_id, order_num) VALUES (1,1,1);
INSERT INTO sessions_songs (session_id, song_id, order_num) VALUES (1,2,2);
INSERT INTO sessions_songs (session_id, song_id, order_num) VALUES (1,3,3);
INSERT INTO sessions_songs (session_id, song_id, order_num) VALUES (1,4,4);
INSERT INTO sessions_songs (session_id, song_id, order_num) VALUES (1,5,5);
INSERT INTO sessions_songs (session_id, song_id, order_num) VALUES (1,6,6);
INSERT INTO sessions_songs (session_id, song_id, order_num) VALUES (1,7,7);
INSERT INTO sessions_songs (session_id, song_id, order_num) VALUES (1,8,8);
INSERT INTO sessions_songs (session_id, song_id, order_num) VALUES (1,9,9);
INSERT INTO sessions_songs (session_id, song_id, order_num) VALUES (1,10,10);
INSERT INTO sessions_songs (session_id, song_id, order_num) VALUES (1,11,11);
INSERT INTO sessions_songs (session_id, song_id, order_num) VALUES (1,12,12);
INSERT INTO sessions_songs (session_id, song_id, order_num) VALUES (2,8,1);
INSERT INTO sessions_songs (session_id, song_id, order_num) VALUES (2,9,2);
INSERT INTO sessions_songs (session_id, song_id, order_num) VALUES (2,7,3);
INSERT INTO sessions_songs (session_id, song_id, order_num) VALUES (3,6,1);
INSERT INTO sessions_songs (session_id, song_id, order_num) VALUES (3,10,2);
INSERT INTO sessions_songs (session_id, song_id, order_num) VALUES (3,11,3);
INSERT INTO sessions_songs (session_id, song_id, order_num) VALUES (3,3,4);
INSERT INTO sessions_songs (session_id, song_id, order_num) VALUES (4,106,1);
INSERT INTO sessions_songs (session_id, song_id, order_num) VALUES (4,12,2);
INSERT INTO sessions_songs (session_id, song_id, order_num) VALUES (4,8,3);
INSERT INTO sessions_songs (session_id, song_id, order_num) VALUES (4,12,2);
INSERT INTO sessions_songs (session_id, song_id, order_num) VALUES (5,2,1);
INSERT INTO sessions_songs (session_id, song_id, order_num) VALUES (5,4,2);
INSERT INTO sessions_songs (session_id, song_id, order_num) VALUES (5,5,3);